### ISSUE TITLE
✨ refactor: Implement refactor entity

### ISSUE THREAD

**Issue by KmYgJn** [KakaoTech-14-All-in-one-move/AIM-14-BE#22]
# Title

- 엔티티에 @PersistenceCreator 추가겸 엔티티 코드 수정

# TODO

- [x] builder -> 팩토리 메서드
- [x] respository 오타 수정
- [x] 이전에 username -> email 에 따른 테스트 코드 변경
- [x] set메소드대신 @Setter 추가
- [x] 정적팩토리 메서드 추가

# etc
- 큐큐
