### ISSUE TITLE
✨ feat: Implement server domain

### ISSUE THREAD

**Issue by KmYgJn** [KakaoTech-14-All-in-one-move/AIM-14-BE#27]
# Title

- 서버 데이터베이스 추가

# TODO

- [x] schema.sql에 서버 데이터 추가
- [x] server domain 생성
- [x] server service 생성
- [x] server controller 생성
- [x] server repository 생성
- [x] server 추가, 삭제 구현
- [x] 이름 변경 구현
- [x] 이미지 변경 구현
- [x] 멤버 초대 구현

# etc

- 어쩌구저쩌구
