### ISSUE TITLE
✨ feat: Implement channel domain

### ISSUE THREAD

**Issue by KmYgJn** [KakaoTech-14-All-in-one-move/AIM-14-BE#28]
# Title

- 채널 데이터베이스 추가

# TODO

- [x] schema.sql에 채널 데이터베이스 추가
- [x] channel domain 생성
- [x] channel service 생성
- [x] channel controller 생성
- [x] channel repository 생성
- [x] channel 추가, 삭제 구현
- [x] channel (채팅, 음성, 화상) 별로 나누어 지도록 구현

# etc

- 어쩌구저쩌구
