### ISSUE TITLE
🐛 fix: bug

### ISSUE THREAD

**Issue by KmYgJn** [KakaoTech-14-All-in-one-move/AIM-14-BE#57]
# Title

- 버그 수정

# TODO

- [ ] 클라이언트 서버, 채널 동기화
- [ ] 서버 생성 시 기본 채팅, 음성, 화상 채널 1개씩 있도록 수정
- [x] 채팅 채널 이전 메시지들 이미지, 이름 동기화

# etc

- 흐읍
